### ISSUE TITLE
FlatList keyExtractor

### ISSUE THREAD

**Issue by iConrado** [Root-App/react-native-mock-render#46] opened 2018-05-08 03:52 UTC
Hello there! Congratulations for creating this amazing code. It is very useful.

I'm using FlatList with a keyExtrator prop, that provide an automatic key to the rendered items.

Like this: 
```
<FlatList
  data={this.state.itens}
  removeClippedSubviews={false}
  keyExtractor={(item, index) => index.toString()}
  renderItem={({ item }) => <CustomComponent item={item} removerItem={this.removerItem} />}
/>
```
But I got the error bellow: 

``` 
    console.error node_modules/fbjs/lib/warning.js:33
        Warning: Each child in an array or iterator should have a unique "key" prop.

    Check the render method of `FlatList`. See https://fb.me/react-warning-keys for more information.
        in ItemDespensa (created by FlatList)
        in FlatList (created by ListaDespensa)
        in react-native-mock (created by ScrollView)
        in ScrollView (created by ListaDespensa)
        in react-native-mock (created by View)
        in View (created by ListaDespensa)
        in ListaDespensa (created by WrapperComponent)
        in WrapperComponent
```

Would you have any solution about this?

Thanks!

**Comment by bob-carson** [comment] 2018-08-09 21:01
Hi @iConrado.  It looks like this is a bug caused by the fact that the mock implementation of `FlatList` does not respect the `keyExtractor` prop.  [See the `_renderChildren` method](https://github.com/Root-App/react-native-mock-render/blob/master/src/components/FlatList.js#L126-L138)  Thanks for bringing this up!

If you'd like to contribute to this project you are welcome to submit a pull request fixing the bug.  If you do, make sure that you add unit tests that fail before your change and pass after.  Also make sure the rest of the tests and the linter pass to help us get your change merged and release as soon as possible.

**Comment by Quadriphobs1** [comment] 2018-08-26 09:44
@iConrado Add Key to your renderItem component

**Comment by Quadriphobs1** [comment] 2018-08-26 09:45
```<FlatList
  data={this.state.itens}
  removeClippedSubviews={false}
  keyExtractor={(item, index) => index.toString()}
  renderItem={({ item }) => <CustomComponent key={item.id | index} item={item} removerItem={this.removerItem} />}
/>```

**Closed** 2019-12-30 16:08 UTC
Labels: bug
